yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
    "@nestjs/core@*":
        peerDependencies:
            "class-validator": "*"
            "class-transformer": "*"

        peerDependenciesMeta:
            "class-validator":
                optional: true
            "class-transformer":
                optional: true
            "@nestjs/platform-express":
                optional: true
